# Generated by Django 4.1.7 on 2023-02-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=200)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('dt', models.IntegerField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('feels_like', models.FloatField(default=0)),
                ('temp_min', models.FloatField(default=0)),
                ('temp_max', models.FloatField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('sea_level', models.IntegerField(default=0)),
                ('grnd_level', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('temp_kf', models.FloatField(default=0)),
                ('weather_id', models.IntegerField(default=0)),
                ('weather_main', models.CharField(max_length=200)),
                ('weather_description', models.CharField(max_length=200)),
                ('clouds_all', models.IntegerField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
                ('wind_deg', models.FloatField(default=0)),
                ('wind_gust', models.FloatField(default=0)),
                ('visibility', models.FloatField(default=0)),
                ('df_txt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameSchedule',
            fields=[
                ('game_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sport_key', models.CharField(max_length=200)),
                ('sport_title', models.CharField(max_length=200)),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('city_name', models.CharField(max_length=200)),
                ('timezone', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('city_id', models.IntegerField(default=0)),
                ('stadium_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('home_team', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=200)),
                ('bookmaker_title', models.CharField(max_length=200)),
                ('last_update', models.CharField(max_length=200)),
                ('market_type', models.CharField(max_length=200)),
                ('over_price', models.FloatField(default=0)),
                ('over_point', models.FloatField(default=0)),
                ('under_price', models.FloatField(default=0)),
                ('under_point', models.FloatField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.gameschedule')),
            ],
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='stadium_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.stadiums'),
        ),
    ]
