# Generated by Django 4.1.7 on 2023-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_remove_gameschedule_stadium_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiums',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecast',
            name='city_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stadiums',
            name='stadium_name',
            field=models.CharField(max_length=200),
        ),
    ]
