# Generated by Django 4.1.7 on 2023-02-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_stadiums_id_alter_forecast_city_id_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='stadiums',
            name='id',
        ),
        migrations.AlterField(
            model_name='stadiums',
            name='home_team',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='forecast',
            name='home_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='baseball.stadiums'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameschedule',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.stadiums'),
        ),

    ]
